# Generated by Django 5.1.2 on 2024-11-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image', verbose_name='аватарка пользователя'),
        ),
    ]
